// <auto-generated />
using System;
using ChivoFlixDesktop.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChivoFlixDesktop.Migrations
{
    [DbContext(typeof(masterContext))]
    [Migration("20220411004702_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ChivoFlixDesktop.Model.Generos", b =>
                {
                    b.Property<int>("IdGeneros")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idGeneros")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnName("nombre")
                        .HasColumnType("varchar(25)")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.HasKey("IdGeneros")
                        .HasName("PK__GENEROS__525F69B8029B802E");

                    b.ToTable("GENEROS");
                });

            modelBuilder.Entity("ChivoFlixDesktop.Model.Listado", b =>
                {
                    b.Property<int>("IdListado")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idListado")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdPeliculas")
                        .HasColumnName("idPeliculas")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarios")
                        .HasColumnName("idUsuarios")
                        .HasColumnType("int");

                    b.HasKey("IdListado")
                        .HasName("PK__LISTADO__EEA3B4655F537D8E");

                    b.HasIndex("IdPeliculas");

                    b.HasIndex("IdUsuarios");

                    b.ToTable("LISTADO");
                });

            modelBuilder.Entity("ChivoFlixDesktop.Model.Peliculas", b =>
                {
                    b.Property<int>("IdPeliculas")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idPeliculas")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnioEstreno")
                        .HasColumnName("anioEstreno")
                        .HasColumnType("int");

                    b.Property<string>("Banner")
                        .IsRequired()
                        .HasColumnName("banner")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("Calidad")
                        .IsRequired()
                        .HasColumnName("calidad")
                        .HasColumnType("varchar(5)")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("CategoriaEdad")
                        .IsRequired()
                        .HasColumnName("categoriaEdad")
                        .HasColumnType("varchar(3)")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnName("descripcion")
                        .HasColumnType("varchar(500)")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnName("director")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<int>("IdGeneros")
                        .HasColumnName("idGeneros")
                        .HasColumnType("int");

                    b.HasKey("IdPeliculas")
                        .HasName("PK__PELICULA__71DB443F076FB354");

                    b.HasIndex("IdGeneros");

                    b.ToTable("PELICULAS");
                });

            modelBuilder.Entity("ChivoFlixDesktop.Model.Planes", b =>
                {
                    b.Property<int>("IdPlanes")
                        .HasColumnName("idPlanes")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarios")
                        .HasColumnName("idUsuarios")
                        .HasColumnType("int");

                    b.Property<string>("Planes1")
                        .IsRequired()
                        .HasColumnName("planes")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.HasKey("IdPlanes")
                        .HasName("PK__PLANES__31C4681E6A8EB528");

                    b.HasIndex("IdUsuarios");

                    b.ToTable("PLANES");
                });

            modelBuilder.Entity("ChivoFlixDesktop.Model.Roles", b =>
                {
                    b.Property<int>("IdRoles")
                        .HasColumnName("id_roles")
                        .HasColumnType("int");

                    b.Property<int?>("Rol")
                        .HasColumnName("rol")
                        .HasColumnType("int");

                    b.HasKey("IdRoles")
                        .HasName("PK__roles__C73330E7BED09827");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("ChivoFlixDesktop.Model.Tarjetas", b =>
                {
                    b.Property<int>("IdTarjetas")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idTarjetas")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cvv")
                        .HasColumnName("CVV")
                        .HasColumnType("int");

                    b.Property<string>("FechaVencimiento")
                        .IsRequired()
                        .HasColumnName("fechaVencimiento")
                        .HasColumnType("varchar(5)")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<int>("IdUsuarios")
                        .HasColumnName("idUsuarios")
                        .HasColumnType("int");

                    b.Property<string>("NumeroTarjeta")
                        .IsRequired()
                        .HasColumnName("numeroTarjeta")
                        .HasColumnType("varchar(16)")
                        .HasMaxLength(16)
                        .IsUnicode(false);

                    b.HasKey("IdTarjetas")
                        .HasName("PK__TARJETAS__B6CCF1D9550EEA0A");

                    b.HasIndex("IdUsuarios");

                    b.ToTable("TARJETAS");
                });

            modelBuilder.Entity("ChivoFlixDesktop.Model.Usuarios", b =>
                {
                    b.Property<int>("IdUsuarios")
                        .HasColumnName("id_usuarios")
                        .HasColumnType("int");

                    b.HasKey("IdUsuarios")
                        .HasName("PK__usuarios__854B73B303E44E5D");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("ChivoFlixDesktop.Model.Listado", b =>
                {
                    b.HasOne("ChivoFlixDesktop.Model.Peliculas", "IdPeliculasNavigation")
                        .WithMany("Listado")
                        .HasForeignKey("IdPeliculas")
                        .HasConstraintName("fk_Listado_Peliculas")
                        .IsRequired();

                    b.HasOne("ChivoFlixDesktop.Model.Usuarios", "IdUsuariosNavigation")
                        .WithMany("Listado")
                        .HasForeignKey("IdUsuarios")
                        .HasConstraintName("fk_Listado_Usuarios")
                        .IsRequired();
                });

            modelBuilder.Entity("ChivoFlixDesktop.Model.Peliculas", b =>
                {
                    b.HasOne("ChivoFlixDesktop.Model.Generos", "IdGenerosNavigation")
                        .WithMany("Peliculas")
                        .HasForeignKey("IdGeneros")
                        .HasConstraintName("fk_Peliculas_Generos")
                        .IsRequired();
                });

            modelBuilder.Entity("ChivoFlixDesktop.Model.Planes", b =>
                {
                    b.HasOne("ChivoFlixDesktop.Model.Usuarios", "IdUsuariosNavigation")
                        .WithMany("Planes")
                        .HasForeignKey("IdUsuarios")
                        .HasConstraintName("fk_Planes_Usuarios")
                        .IsRequired();
                });

            modelBuilder.Entity("ChivoFlixDesktop.Model.Tarjetas", b =>
                {
                    b.HasOne("ChivoFlixDesktop.Model.Usuarios", "IdUsuariosNavigation")
                        .WithMany("Tarjetas")
                        .HasForeignKey("IdUsuarios")
                        .HasConstraintName("fk_Tarjetas_Usuarios")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
